### ISSUE TITLE
FR: customizable created-date property

### ISSUE THREAD

**Issue by Moyf** [bartkessels/daily-note-calendar#40]
Hello!
I'm using Sync service to sync files between my different devices, and sometimes the "file creation date"  is not the actual "created date of this note" but the date when the file is synced in this device.

To solve this, I maintain the date properties by myself with some plugins:
![image](https://github.com/user-attachments/assets/3e86e314-f721-4484-8c28-5d8d726d3b05)

Based on this, I'm wondering could you provide a customizable "created date property" setting for this option:
![image](https://github.com/user-attachments/assets/13d4036b-82b2-432a-8f05-b6926428924a)

So that users like me can take the `created_date` property from the frontmatter as the "Created date" and then display the correct notes under a date?

**Comment by bartkessels** [comment]
Hello, thanks for your feedback. I like the idea of having an option to use a different value as the creation date. This also makes sense to me, because I’ve had notes show up with the wrong creation date as well but I thought it was someting I’ve done wrong. Didn’t realise that it was probably the sync service. 

As for the update were this will land, it’ll be after the two other feature requests that are open. So I can’t give you am estimation as to when I’ll be anle to pick it up. But it will be added in a future release, until then I’ll keep this issue open. 

For now, I hooe you’ll still enjoy the plugin and keep the feature requests and bug reports coming!

**Comment by Moyf** [comment]
> Hello, thanks for your feedback. I like the idea of having an option to use a different value as the creation date. This also makes sense to me, because I’ve had notes show up with the wrong creation date as well but I thought it was someting I’ve done wrong. Didn’t realise that it was probably the sync service.
> 
> As for the update were this will land, it’ll be after the two other feature requests that are open. So I can’t give you am estimation as to when I’ll be anle to pick it up. But it will be added in a future release, until then I’ll keep this issue open.
> 
> For now, I hooe you’ll still enjoy the plugin and keep the feature requests and bug reports coming!

Haha, no problem! Glad that this information could be helpful to you  :D 

And I think I can share more - personally I would use Templater plugin to write the `created_date` property when creating a note, and use **Update Time Updater** plugin to update the `modified_date` (There are many similar plugins can do this)

**Comment by bartkessels** [comment]
Good day, I've updated the plugin to add two new settings to allow this behaviour. One to enable the use of properties to retrieve the created on date, and one to specify the property name.

<img width="1737" alt="Screenshot 2024-12-21 at 14 39 04" src="https://github.com/user-attachments/assets/75330d16-0a7f-4195-b2ed-e174ed5bc73d" />

Hopefully this is what you expected, otherwise feel free to let me know. As for this update, it will be released in version 1.9.0.

**Comment by bartkessels** [comment]
Release 1.9.0 has just been launched, so the next time you update the plugin in Obsidian you should be able to use your own properties to list the notes created on the selected date.

Again thanks for your feature request and if you have any more questions or feedback keep them coming!

**Comment by Moyf** [comment]
Great news, thank you!
