### ISSUE TITLE
Monthly, Quarterly & Yearly note support & calendar UI

### ISSUE THREAD

**Issue by helpimfalling** [bartkessels/daily-note-calendar#5]
I'm glad someone is updating the calendar plugin! I'd love additional support for Monthly, Quarterly & Yearly notes, as well as the ability to reach current Monthly, Quarterly & Yearly notes from the UI.

**Comment by bartkessels** [comment]
Thanks for using the plugin and your feedback. As of right now I'm rewriting parts of the plugin to allow for more extensibility, which will also include monthly notes. But I'm going to add yearly notes as well!

As for the quarterly notes, I need to think of a good way to incorporate that into the plugin so it's easy to find and use (because there's no indication for a quarter year in the UI).

Hopefully this gives you some hope and in the mean time I hope you'll use the plugin with joy. And as always, if you have any more feedback or suggestions keep them coming!

**Comment by Moyf** [comment]
*Raise hand* Want this feature too!

Given that the other Calendar plugins are no longer maintained, I put my last hope in this plugin, hahaha (No pressure, just kidding :P  )

**Comment by bartkessels** [comment]
Hello to the both of you, I have some great news! I've added support for monthly and yearly notes in the upcoming release, right now the automatic pipeline is still crunching away. So the updated version will be with you shortly.

And @Moyf I saw that you cloned some other calendar plugin repositories, so if you'd like to contribute to this plugin you're more than welcome. Also, I don't feel the pressure just yet 😂.

As far as the quarterly notes go, I'll leave this issue open until those have been added. I have some ideas as what some solution might be to integrate them into the UI (next to the month and year add the quarter like this: _November 2024 Q4_). If you have another suggestion I'd be happy to hear them.

Have a nice day, and again thanks for using the plugin!

**Comment by bartkessels** [comment]
Okay, I got bored and decided to add quarterly note support right now, so in the next release (1.2.0) you have the following periodic notes support

- Daily notes (as before)
- Weekly notes (as before)
- Monthly notes
- Quarterly notes
- Yearly notes

Again thank you for your feedback, and please keep it coming!
